### ISSUE TITLE
FMS Speed and Flaps/Gear Logic

### ISSUE THREAD

**Issue by 997R8V10** [Sauna-ATC-Training-Simulator/sauna-api#80]
- Always have gear down on ground
- Implement TO Logic:
  - Sfc-> 1000' AFE LNAV | TO. Speed should be ~V2
  - 1000': LNAV | FLCH. Speed should increase to the correct value for climb
- Implement Approach speeds
- Implement FMS Speed for climb, cruise, descent, approach

**Comment by OdiasUkcamaj** [comment]
Implemented FMS Speed and Flaps/Gear Logic, plus added new FSD features as well as tweaking other minor bugs.
